[project]
name = "img-to-pdf"
version = "0.1.0"
description = "Convert any image list to pdf continuous file"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pillow>=11.0.0",
    "reportlab>=4.2.5",
]
